baseURL = "http://nmlakra.github.io/blog/"
languageCode = "en-us"
title = "Nikhil Mark Lakra"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  math = true

[permalinks]
  posts = "/posts/:title/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

